export const LAYOUT_ANIMATION_DURATION = 200;

export const CONTENT_CONTAINER_PADDING_START = 16;
export const CONTENT_CONTAINER_GAP = 16;

export const CONTAINER_PADDING_VERTICAL = 12;
export const COMPACT_CONTAINER_PADDING_VERTICAL = 12;

export const EDIT_BUTTON_CONTAINER_WIDTH = 36; // TODO
export const GRABBER_CONTAINER_WIDTH = 50; // TODO
