export const LAYOUT_ANIMATION_DURATION = 300;

export const CONTENT_CONTAINER_PADDING_START = 16;
export const CONTENT_CONTAINER_GAP = 16;

export const CONTAINER_PADDING_VERTICAL = 12;
export const COMPACT_CONTAINER_PADDING_VERTICAL = 8;
export const CONTAINER_PADDING_END = 24;

export const EDIT_BUTTON_CONTAINER_WIDTH = 40;
export const GRABBER_CONTAINER_WIDTH = 50;

export const SEPARATOR_COLOR_NAME = 'outlineVariant' as const;
